package AplikasiSwalayan.laporan;

import AplikasiSwalayan.Menu;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import database.koneksi;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import session.UserSession;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hakim
 */
public class laporanPembelian extends javax.swing.JInternalFrame {
    private DefaultTableModel data;
    private Connection conn = new koneksi().connect();
    ResultSet rs;
    JasperReport JasperReport;
    JasperDesign JasperDesign;
    JasperPrint JasperPrint;
    Map<String, Object> param = new HashMap<>();
    /**
     * Creates new form dataKonsumen
     */
    public laporanPembelian() {
        initComponents();
        
        
        this.setBorder(null);
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        tabelPembelian();
        
    }
    
    protected void kosong() {
        tKodeTr.setText("");
        tKodeKaryawan.setText("");
        tNamaKaryawan.setText("");
        tKodeSuplier.setText("");
        tNamaSuplier.setText("");
        tTanggal.setDate(new Date());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPembelian = new javax.swing.JTable();
        bPrintAll = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        bNota = new javax.swing.JButton();
        tTglSampai = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        tKodeKaryawan = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tNamaKaryawan = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        tKodeSuplier = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tNamaSuplier = new javax.swing.JTextField();
        tTglDari = new com.toedter.calendar.JDateChooser();
        tTanggal = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        tKodeTr = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bDelete = new javax.swing.JButton();
        bCari = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setResizable(true);
        setTitle("Data Konsumen");
        setMinimumSize(new java.awt.Dimension(0, 0));
        setName(""); // NOI18N

        tabelPembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPembelianMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelPembelian);

        bPrintAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/print-icon2.png"))); // NOI18N
        bPrintAll.setText("Cetak Data Transaksi Pembelian");
        bPrintAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrintAllActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Laporan Transaksi Pembelian");

        bNota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/print-icon2.png"))); // NOI18N
        bNota.setText("Cetak Nota");
        bNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNotaActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Karyawan"));

        jLabel19.setText("ID Karyawan");

        tKodeKaryawan.setEnabled(false);

        jLabel20.setText("Nama");

        tNamaKaryawan.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNamaKaryawan))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tKodeKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tKodeKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Suplier\n"));

        jLabel23.setText("ID Suplier");

        tKodeSuplier.setEnabled(false);

        jLabel24.setText("Nama");

        tNamaSuplier.setEnabled(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNamaSuplier))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tKodeSuplier, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tKodeSuplier, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNamaSuplier, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tTanggal.setEnabled(false);

        jLabel1.setText("Kode Transaksi");

        tKodeTr.setEnabled(false);
        tKodeTr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKodeTrActionPerformed(evt);
            }
        });

        jLabel3.setText("Tanggal");

        bDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/Delete.png"))); // NOI18N
        bDelete.setText(" DELETE");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        bCari.setText("Cari");
        bCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariActionPerformed(evt);
            }
        });

        jLabel2.setText("Cari Transaksi dari");

        jLabel4.setText("sampai");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(22, 22, 22)
                                        .addComponent(tKodeTr, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(tTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tTglDari, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tTglSampai, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bCari))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(bPrintAll, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tKodeTr, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tTglSampai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tTglDari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bNota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bDelete)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bPrintAll)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bPrintAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrintAllActionPerformed
        // TODO add your handling code here:
        File file = new File("src/Laporan/semuaPembelian.jrxml");
        HashMap hash = new HashMap();
        SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");
        String tglDari = String.valueOf(fm.format(tTglDari.getDate()));
        String tglSampai = String.valueOf(fm.format(tTglSampai.getDate()));
        hash.put("NAMA_KARYAWAN", UserSession.getNama_karyawan());
        hash.put("TGL_DARI", tglDari);
        hash.put("TGL_SAMPAI", tglSampai);
        try {
            JasperDesign = JRXmlLoader.load(file);
            JasperReport = JasperCompileManager.compileReport(JasperDesign);
            JasperPrint = JasperFillManager.fillReport(JasperReport, hash, conn);
            JasperViewer.viewReport(JasperPrint, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, "Gagal Cetak"+e);
        }
        kosong();
    }//GEN-LAST:event_bPrintAllActionPerformed

    private void tabelPembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPembelianMouseClicked
        SimpleDateFormat tglview = new SimpleDateFormat("yyyy-MM-dd");   
        
        Date dateView = null;
        int baris = tabelPembelian.getSelectedRow();
        try {
            dateView = tglview.parse((String) tabelPembelian.getValueAt(baris, 4));
        } catch (ParseException ex) {
            Logger.getLogger(laporanPembelian.class.getName()).log(Level.SEVERE, null, ex);
        }        
        
        tKodeTr.setText(tabelPembelian.getModel().getValueAt(baris, 0).toString());
        tKodeKaryawan.setText(tabelPembelian.getModel().getValueAt(baris, 5).toString());
        tNamaKaryawan.setText(tabelPembelian.getModel().getValueAt(baris,1).toString());
        tKodeSuplier.setText(tabelPembelian.getModel().getValueAt(baris, 6).toString());
        tNamaSuplier.setText(tabelPembelian.getModel().getValueAt(baris, 2).toString());
        tTanggal.setDate(dateView);
    }//GEN-LAST:event_tabelPembelianMouseClicked

    private void bNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNotaActionPerformed
        // TODO add your handling code here:
        File file = new File("src/Laporan/notaPembelian.jrxml");
        HashMap hash = new HashMap();
        hash.put("kd_transaksi", tKodeTr.getText());
        try {
            JasperDesign = JRXmlLoader.load(file);
            JasperReport = JasperCompileManager.compileReport(JasperDesign);
            JasperPrint = JasperFillManager.fillReport(JasperReport, hash, conn);
            JasperViewer.viewReport(JasperPrint, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, "Gagal Cetak"+e);
        }
        
    }//GEN-LAST:event_bNotaActionPerformed

    private void tKodeTrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKodeTrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tKodeTrActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"Hapus data ini?","Konfirmasi",JOptionPane.YES_NO_OPTION);
         if (ok==0){
             
             String sql = "delete from transaksi_pembelian_detail where kd_transaksi_beli = '"+tKodeTr.getText()+"'";
        
             String sql2 = "delete from transaksi_pembelian where kd_transaksi_beli ='"+tKodeTr.getText()+"'";
             try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                PreparedStatement stat2 = conn.prepareStatement(sql2);
                stat2.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data akan di hapus dari sistem?");
                kosong();
                tKodeTr.requestFocus();
             }
                catch (SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+e);
             }
         tabelPembelian();
         }
    }//GEN-LAST:event_bDeleteActionPerformed

    private void bCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariActionPerformed
        // TODO add your handling code here:
        Object header[]={"Kode Transaksi","NAMA KARYAWAN","NAMA SUPLIER", "TOTAL", "TANGGAL", "kdkar", "kdkons"};
        DefaultTableModel data=new DefaultTableModel(null,header);
        tabelPembelian.setModel(data);
        
        
        SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");   
        String tglDari = String.valueOf(fm.format(tTglDari.getDate()));
        String tglSampai = String.valueOf(fm.format(tTglSampai.getDate()));
        
        String sql="SELECT " 
                + "tp.kd_transaksi_beli, " 
                +"sum(p.harga_beli * tpd.jumlah) as total,"
                + "k.kd_karyawan, k.nama_karyawan, " 
                + "s.kd_suplier, s.nama_suplier, " 
                + "p.kd_produk, p.nama_produk, jumlah , p.harga_beli, tgl_pembelian " 
                + "FROM transaksi_pembelian as tp " 
                + "INNER JOIN transaksi_pembelian_detail as tpd " 
                + "ON tp.kd_transaksi_beli = tpd.kd_transaksi_beli " 
                + "INNER JOIN  karyawan as k " 
                + "ON tp.kd_karyawan = k.kd_karyawan " 
                + "INNER JOIN suplier as s " 
                + "ON tp.kd_suplier = s.kd_suplier " 
                + "INNER JOIN produk as p " 
                + "ON tpd.kd_produk = p.kd_produk "
                +"WHERE (tgl_pembelian BETWEEN ? AND ?) "
                +"GROUP BY tp.kd_transaksi_beli";
        
        try {
             PreparedStatement stm = conn.prepareStatement(sql,ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
             stm.setString(1, tglDari);
             stm.setString(2, tglSampai);
             ResultSet rs=stm.executeQuery();
            while (rs.next())
            {
                String kolom1=rs.getString("kd_transaksi_beli");
                String kolom2=rs.getString("nama_karyawan");
                String kolom3=rs.getString("nama_suplier");
                String kolom4=rs.getString("total");
                String kolom5=rs.getString("tgl_pembelian");
                String kolom6=rs.getString("kd_karyawan");
                String kolom7=rs.getString("kd_suplier");

                String kolom[]={kolom1,kolom2,kolom3,kolom4,kolom5,kolom6,kolom7};
                data.addRow(kolom);
            }
            tabelPembelian.removeColumn(tabelPembelian.getColumnModel().getColumn(6));
            tabelPembelian.removeColumn(tabelPembelian.getColumnModel().getColumn(5));
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "gagal login: "+e);     
	}
    }//GEN-LAST:event_bCariActionPerformed
    
    public void tabelPembelian(){
        Object header[]={"Kode Transaksi","NAMA KARYAWAN","NAMA SUPLIER", "TOTAL", "TANGGAL","kdkar", "kdkons"};
        DefaultTableModel data=new DefaultTableModel(null,header);
        tabelPembelian.setModel(data);
        String sql="SELECT " 
                + "tp.kd_transaksi_beli, " 
                +"sum(p.harga_beli * tpd.jumlah) as total,"
                + "k.kd_karyawan, k.nama_karyawan, " 
                + "s.kd_suplier, s.nama_suplier, " 
                + "p.kd_produk, p.nama_produk, jumlah , p.harga_beli, tgl_pembelian " 
                + "FROM transaksi_pembelian as tp " 
                + "INNER JOIN transaksi_pembelian_detail as tpd " 
                + "ON tp.kd_transaksi_beli = tpd.kd_transaksi_beli " 
                + "INNER JOIN  karyawan as k " 
                + "ON tp.kd_karyawan = k.kd_karyawan " 
                + "INNER JOIN suplier as s " 
                + "ON tp.kd_suplier = s.kd_suplier " 
                + "INNER JOIN produk as p " 
                + "ON tpd.kd_produk = p.kd_produk "
                +"GROUP BY tp.kd_transaksi_beli";
        try {
            Statement stm = conn.createStatement();
            ResultSet rs=stm.executeQuery(sql);
            while (rs.next())
            {
                String kolom1=rs.getString("kd_transaksi_beli");
                String kolom2=rs.getString("nama_karyawan");
                String kolom3=rs.getString("nama_suplier");
                String kolom4=rs.getString("total");
                String kolom5=rs.getString("tgl_pembelian");
                String kolom6=rs.getString("kd_karyawan");
                String kolom7=rs.getString("kd_suplier");

                String kolom[]={kolom1,kolom2,kolom3,kolom4,kolom5,kolom6,kolom7};
                data.addRow(kolom);
            }
            tabelPembelian.removeColumn(tabelPembelian.getColumnModel().getColumn(6));
            tabelPembelian.removeColumn(tabelPembelian.getColumnModel().getColumn(5));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal dipanggil"+e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCari;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bNota;
    private javax.swing.JButton bPrintAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField tKodeKaryawan;
    public javax.swing.JTextField tKodeSuplier;
    private javax.swing.JTextField tKodeTr;
    public javax.swing.JTextField tNamaKaryawan;
    public javax.swing.JTextField tNamaSuplier;
    private com.toedter.calendar.JDateChooser tTanggal;
    private com.toedter.calendar.JDateChooser tTglDari;
    private com.toedter.calendar.JDateChooser tTglSampai;
    private javax.swing.JTable tabelPembelian;
    // End of variables declaration//GEN-END:variables
}
