package AplikasiSwalayan;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import java.awt.Image;
import AplikasiSwalayan.transaksi.*;
import AplikasiSwalayan.laporan.*;
import javax.swing.JOptionPane;
import session.UserSession;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hakim
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.getContentPane().setBackground(new Color(126, 196, 207)); 
        showDate();
        setName();
    }

    protected void removeInternalFrame() {
        jDesktopPane1.removeAll();
        jDesktopPane1.updateUI();
    }
    
    void showDate() {
        Date date = new Date();
        SimpleDateFormat ft = new SimpleDateFormat ("E, dd/MM/yyyy");
        lDate.setText(ft.format(date));
    }
    
    private void setName() {
        lnama.setText("Hi, "+UserSession.getNama_karyawan());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/assets/background-pane.png"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g) {
                super.paintComponent(g);
                //        g.setColor(new java.awt.Color(255,255,255));
                //        g.fillRect(0, 0, getWidth(), getHeight());
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        lDate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lnama = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        menuKonsumen = new javax.swing.JMenuItem();
        menuKaryawan = new javax.swing.JMenuItem();
        menuSuplier = new javax.swing.JMenuItem();
        menuProduk = new javax.swing.JMenuItem();
        menuKategori = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        menuPembelian = new javax.swing.JMenuItem();
        menuPenjualan = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuLaporanKaryawan = new javax.swing.JMenuItem();
        menuLaporanKonsumen = new javax.swing.JMenuItem();
        menuLaporanSuplier = new javax.swing.JMenuItem();
        menuLaporanProduk = new javax.swing.JMenuItem();
        menuLaporanKategori = new javax.swing.JMenuItem();
        menuLaporanPembelian = new javax.swing.JMenuItem();
        menuLaporanPenjualan = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setBackground(new java.awt.Color(126, 196, 207));
        setMinimumSize(new java.awt.Dimension(1029, 676));

        jDesktopPane1.setBackground(new java.awt.Color(0, 0, 0));
        jDesktopPane1.setForeground(new java.awt.Color(250,250,250));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(51, 102, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("PT. SUPERHERO");

        lDate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lDate.setText("Sun, 22/07/2008");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Superhero_Logo_3.png"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(51, 102, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel3.setText("Sistem Monitoring Transaksi Penjualan");

        lnama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lnama.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lnama.setText("HI, Hakim");

        fileMenu.setMnemonic('f');
        fileMenu.setText("Master");

        menuKonsumen.setText("Konsumen");
        menuKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKonsumenActionPerformed(evt);
            }
        });
        fileMenu.add(menuKonsumen);

        menuKaryawan.setText("Karyawan");
        menuKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKaryawanActionPerformed(evt);
            }
        });
        fileMenu.add(menuKaryawan);

        menuSuplier.setText("Suplier");
        menuSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSuplierActionPerformed(evt);
            }
        });
        fileMenu.add(menuSuplier);

        menuProduk.setText("Produk");
        menuProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdukActionPerformed(evt);
            }
        });
        fileMenu.add(menuProduk);

        menuKategori.setText("Kategori");
        menuKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKategoriActionPerformed(evt);
            }
        });
        fileMenu.add(menuKategori);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Transaksi");

        menuPembelian.setText("Pembelian");
        menuPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPembelianActionPerformed(evt);
            }
        });
        editMenu.add(menuPembelian);

        menuPenjualan.setText("Penjualan");
        menuPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenjualanActionPerformed(evt);
            }
        });
        editMenu.add(menuPenjualan);

        menuBar.add(editMenu);

        jMenu1.setText("Laporan");

        menuLaporanKaryawan.setText("Karyawan");
        menuLaporanKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanKaryawanActionPerformed(evt);
            }
        });
        jMenu1.add(menuLaporanKaryawan);

        menuLaporanKonsumen.setText("Konsumen");
        menuLaporanKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanKonsumenActionPerformed(evt);
            }
        });
        jMenu1.add(menuLaporanKonsumen);

        menuLaporanSuplier.setText("Suplier");
        menuLaporanSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanSuplierActionPerformed(evt);
            }
        });
        jMenu1.add(menuLaporanSuplier);

        menuLaporanProduk.setText("Produk");
        menuLaporanProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanProdukActionPerformed(evt);
            }
        });
        jMenu1.add(menuLaporanProduk);

        menuLaporanKategori.setText("Kategori");
        menuLaporanKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanKategoriActionPerformed(evt);
            }
        });
        jMenu1.add(menuLaporanKategori);

        menuLaporanPembelian.setText("Pembelian");
        menuLaporanPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanPembelianActionPerformed(evt);
            }
        });
        jMenu1.add(menuLaporanPembelian);

        menuLaporanPenjualan.setText("Penjualan");
        menuLaporanPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanPenjualanActionPerformed(evt);
            }
        });
        jMenu1.add(menuLaporanPenjualan);

        menuBar.add(jMenu1);

        jMenu2.setText("Akun");

        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        jMenu2.add(menuLogout);

        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 888, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lnama, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lnama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lDate)
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDesktopPane1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuKonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKonsumenActionPerformed
        // TODO add your handling code here:
        removeInternalFrame();
        dataKonsumen konsumen = new dataKonsumen();
        jDesktopPane1.add(konsumen);
        konsumen.setVisible(true);
    }//GEN-LAST:event_menuKonsumenActionPerformed

    private void menuKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKaryawanActionPerformed
        // TODO add your handling code here:
        removeInternalFrame();
        dataKaryawan karyawan = new dataKaryawan();
        jDesktopPane1.add(karyawan);
        karyawan.setVisible(true);
    }//GEN-LAST:event_menuKaryawanActionPerformed

    private void menuSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSuplierActionPerformed
        // TODO add your handling code here:
        removeInternalFrame();
        dataSuplier suplier = new dataSuplier();
        jDesktopPane1.add(suplier);
        suplier.setVisible(true);
    }//GEN-LAST:event_menuSuplierActionPerformed

    private void menuProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdukActionPerformed
        // TODO add your handling code here:
        removeInternalFrame();
        dataProduk produk = new dataProduk();
        jDesktopPane1.add(produk);
        produk.setVisible(true);
    }//GEN-LAST:event_menuProdukActionPerformed

    private void menuKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKategoriActionPerformed
        // TODO add your handling code here:
        removeInternalFrame();
        dataKategori kategori = new dataKategori();
        jDesktopPane1.add(kategori);
        kategori.setVisible(true);
    }//GEN-LAST:event_menuKategoriActionPerformed

    private void menuLaporanKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanKaryawanActionPerformed
        // TODO add your handling code here:
        removeInternalFrame();
        laporanKaryawan k = new laporanKaryawan();
        jDesktopPane1.add(k);
        k.setVisible(true);
    }//GEN-LAST:event_menuLaporanKaryawanActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"Anda Yakin ingin Logout?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (ok==0){
            Login back = new Login();
            back.setVisible(true);
            this.dispose();         
        }
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPembelianActionPerformed
        // TODO add your handling code here:
        removeInternalFrame();
        pembelian pem = new pembelian();
        jDesktopPane1.add(pem);
        pem.setVisible(true);
    }//GEN-LAST:event_menuPembelianActionPerformed

    private void menuPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenjualanActionPerformed
        // TODO add your handling code here:
        removeInternalFrame();
        penjualan pen = new penjualan();
        jDesktopPane1.add(pen);
        pen.setVisible(true);
    }//GEN-LAST:event_menuPenjualanActionPerformed

    private void menuLaporanKonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanKonsumenActionPerformed
        // TODO add your handling code here:
        removeInternalFrame();
        laporanKonsumen lk = new laporanKonsumen();
        jDesktopPane1.add(lk);
        lk.setVisible(true);
    }//GEN-LAST:event_menuLaporanKonsumenActionPerformed

    private void menuLaporanProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanProdukActionPerformed
        // TODO add your handling code here:
        removeInternalFrame();
        laporanProduk lp = new laporanProduk();
        jDesktopPane1.add(lp);
        lp.setVisible(true);
    }//GEN-LAST:event_menuLaporanProdukActionPerformed

    private void menuLaporanSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanSuplierActionPerformed
        // TODO add your handling code here:
        removeInternalFrame();
        laporanSuplier ls = new laporanSuplier();
        jDesktopPane1.add(ls);
        ls.setVisible(true);
    }//GEN-LAST:event_menuLaporanSuplierActionPerformed

    private void menuLaporanKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanKategoriActionPerformed
        // TODO add your handling code here:
        removeInternalFrame();
        laporanKategori lk = new laporanKategori();
        jDesktopPane1.add(lk);
        lk.setVisible(true);
    }//GEN-LAST:event_menuLaporanKategoriActionPerformed

    private void menuLaporanPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanPembelianActionPerformed
        // TODO add your handling code here:
        removeInternalFrame();
        laporanPembelian lp = new laporanPembelian();
        jDesktopPane1.add(lp);
        lp.setVisible(true);
    }//GEN-LAST:event_menuLaporanPembelianActionPerformed

    private void menuLaporanPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanPenjualanActionPerformed
        // TODO add your handling code here:
        removeInternalFrame();
        laporanPenjualan lp = new laporanPenjualan();
        jDesktopPane1.add(lp);
        lp.setVisible(true);
    }//GEN-LAST:event_menuLaporanPenjualanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JLabel lDate;
    private javax.swing.JLabel lnama;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuKaryawan;
    private javax.swing.JMenuItem menuKategori;
    private javax.swing.JMenuItem menuKonsumen;
    private javax.swing.JMenuItem menuLaporanKaryawan;
    private javax.swing.JMenuItem menuLaporanKategori;
    private javax.swing.JMenuItem menuLaporanKonsumen;
    private javax.swing.JMenuItem menuLaporanPembelian;
    private javax.swing.JMenuItem menuLaporanPenjualan;
    private javax.swing.JMenuItem menuLaporanProduk;
    private javax.swing.JMenuItem menuLaporanSuplier;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuPembelian;
    private javax.swing.JMenuItem menuPenjualan;
    private javax.swing.JMenuItem menuProduk;
    private javax.swing.JMenuItem menuSuplier;
    // End of variables declaration//GEN-END:variables

}
